### ISSUE TITLE
Name confusion: `bigip` or `f5bigip`?

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi-f5bigip#598]
### Describe what happened

Our docsbot reported this:

> :link: [/registry/packages/f5bigip/](https://www.pulumi.com/registry/packages/f5bigip/) → https://pypi.org/project/pulumi-bigip/ (HTTP_404)
> :link: [/registry/packages/f5bigip/](https://www.pulumi.com/registry/packages/f5bigip/) → https://www.nuget.org/packages/Pulumi.Bigip (HTTP_404)
> :link: [/registry/packages/f5bigip/](https://www.pulumi.com/registry/packages/f5bigip/) → https://github.com/pulumi/pulumi-bigip (HTTP_404)

Looking at the sources, the provider name is configured as:

https://github.com/pulumi/pulumi-f5bigip/blob/537c787ac42d77517f45e9a9968c8058965186f6/provider/resources.go#L91

But the repository is named `pulumi-f5bigip`, which doesn't follow the usual pattern of `pulumi-<name>`. I assume, the newly introduced docs generation uses the configured name from `resources.go`, which leads to wrong package names in `docs/_index.md`:

https://github.com/pulumi/pulumi-f5bigip/blob/537c787ac42d77517f45e9a9968c8058965186f6/docs/_index.md#L10-L14

While the correct package names are:

* Nuget: [Pulumi.F5BigIp](https://www.nuget.org/packages/Pulumi.F5BigIP)
* NPM: [@pulumi/f5bigip](https://www.npmjs.com/package/@pulumi/f5bigip)
* Pypi: [pulumi-f5bigip](https://pypi.org/project/pulumi-f5bigip/)

### Sample program

N/A

### Log output

N/A

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by ringods** [comment]
FYI the registry docs publishing process still has some hardcoded assumptions that the `<name>` of the provider also repeats in the repo name as `pulumi-<name>`. For instance, for community packages, the (short) name of the provider is extracted with regex like this in the GHA workflow:

https://github.com/pulumi/registry/blob/9232607d217762538c4ef4e58f8de672f02faf0e/.github/workflows/generate-package-metadata.yml#L40

**Comment by iwahbe** [comment]
Yikes. @ringods Do you know if there is a issue in the registry for this?

**Comment by ringods** [comment]
There doesn't seem to be one.

**Comment by guineveresaenger** [comment]
I've taken a look at this yesterday, and the issue is as follows:

- `info.Name` is used to fetch information about _the upstream provider_, specifically the final part of the repo name after the last dash ("short name"). Example: if the upstream repo is `terraform-provider-unicorn` and our name is `pulumi-unicorn` then there's no issue either way. In this case, the upstream provider is `bigip` but ours is `f5bigip`.
- The code for extracting the names in the bridge relied on `info.Name` because the above ^^ assumption wasn't clear, and because _most_ of our providers are straight 1:1 matches wrt naming.
-> I think if we adjust the bridge code to get the short name similarly to that regex then this is a simple fix - all we need to do is extract the short name from something that specifically relies on the pulumi repo name.

As an aside, I also discovered that `upstreamRepoPath` is completely useless here, as it is a _go module path_ and the only two valid settings for this info field are `./upstream` (where we use a submodule in the provider) and unset (where the bridge sees an empty string and creates a go module path based on info.Name).
